os:
  - linux
language: cpp
compiler:
  - gcc
env:
  matrix:
    - ARGS=""
  global:
    - CTEST_OUTPUT_ON_FAILURE=1
    - TESTARGS="-DMYSQL_TESTING=on -DPSQL_TESTING=ON -DMYSQL_USER=root -DPSQL_USER=postgres -DPSQL_PASSWORD="
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "52dfMYWsUGBSqOsylkNzitc04iT82dRtYaG7YXJ8aLF4Ei0dmbiNA05vDkxozxKnYO8HveGr0COAOQUPzrXv/DHKIiRaeDbVQEgK3F2afezRzqL8Ul9/IPUy8E8bj1kpz7TQb/4YkLHRfip+oyhCbdtQhxNAnxqo1F1l9GQ6vQo="
before_script:
  - mkdir _build
  - cd _build
script:
  - echo
after_script:
  - if [ -f cov-int/build-log.txt ] ; then cat cov-int/build-log.txt ; fi
# install build dependencies and enable Coverity scan
addons:
  apt:
    packages:
    - libbluetooth-dev
    - libusb-1.0-0-dev
    - libgudev-1.0-dev
    - unixodbc-dev
    - libdbi-dev
    - libdbd-sqlite3
    - libdbd-mysql
    - libdbd-pgsql
    - cmake
    - cmake-data
    - gcc-7
    - g++-7
  coverity_scan:
    project:
      name: "gammu/gammu"
      description: "Build submitted via Travis CI"
    notification_email: michal@cihar.com
    build_command_prepend: "export CC=gcc-7 && export CXX=g++-7 && cov-configure --comptype gcc --compiler `which gcc-7` -- -fPIC && cmake .."
    build_command: make
    branch_pattern: coverity_scan
