name: Documentation

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update apt
        run: apt-get update
      - name: Install apt deps
        run: apt-get install -y libbluetooth-dev libusb-1.0-0-dev libgudev-1.0-dev unixodbc-dev libdbi-dev libdbd-sqlite3 libdbd-mysql libdbd-pgsql cmake cmake-data doxygen
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8
      - name: Install Python deps
        run: pip install -r docs/manual/requirements.txt
      - name: Build HTML docs
        run: make manual-html
      - name: Build PDF docs
        run: make manual-pdf
      - name: Commit documentation changes
        if: github.event_name == 'push' && github.event.ref == 'master'
        run: |
          git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
          cp -r build-configure/docs/manual/html/* gh-pages/
          cp build-configure/docs/manual/latex/*.pdf gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
      - name: Push changes
        if: github.event_name == 'push' && github.event.ref == 'master'
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
